language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BADGE=linux
    - os: osx
      env: BADGE=osx

script:
  - aclocal
  - autoconf
  - ./bootstrap
  - ./configure
  - make -j 4
  - make check
